sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t andrevargas/docker-travisci-aws-test -f Dockerfile.dev .

scripts:
  - docker run -e CI=true andrevargas/docker-travisci-aws-test yarn test